// src/pages/Home.tsx
import React from 'react';
import { Link } from 'react-router-dom';
import { motion } from 'framer-motion';
import { SparklesIcon, ClockIcon, Squares2X2Icon } from '@heroicons/react/24/outline';

const cardVariants = {
    hidden: { opacity: 0, y: 50 },
    visible: (i: number) => ({
        opacity: 1,
        y: 0,
        transition: {
            delay: i * 0.2,
            type: "spring",
            stiffness: 120,
        },
    }),
};

const Home: React.FC = () => {
    const menuItems = [
        {
            to: "/generate-recommendations",
            icon: SparklesIcon,
            title: "Generate Recommendations",
            description: "Get personalized book suggestions based on your taste.",
        },
        {
            to: "/recent-generations",
            icon: ClockIcon,
            title: "Recent Generations",
            description: "View the latest recommendations generated by our AI.",
        },
        {
            to: "/browse-books",
            icon: Squares2X2Icon,
            title: "Browse Books",
            description: "Explore our collection of popular and highly-rated books.",
        },
    ];

    return (
        <div className="text-center p-8">
            <motion.div
                initial={{ opacity: 0, scale: 0.9 }}
                animate={{ opacity: 1, scale: 1 }}
                transition={{ duration: 0.5 }}
            >
                <h2 className="text-4xl font-extrabold text-gray-800 mb-4">
                    Find Your Next Favorite Book
                </h2>
                <p className="text-lg text-gray-600 mb-12 max-w-2xl mx-auto">
                    Our AI-powered engine helps you discover books you'll love.
                    Choose an option below to get started.
                </p>
            </motion.div>

            <div className="grid grid-cols-1 md:grid-cols-3 gap-8 max-w-5xl mx-auto">
                {menuItems.map((item, index) => (
                    <motion.div
                        key={item.to}
                        custom={index}
                        initial="hidden"
                        animate="visible"
                        variants={cardVariants}
                        whileHover={{ scale: 1.05, y: -5, boxShadow: "0px 10px 30px rgba(0, 0, 0, 0.1)" }}
                        className="bg-white rounded-xl shadow-md overflow-hidden"
                    >
                        <Link to={item.to} className="block p-8 h-full">
                            <item.icon className="h-12 w-12 mx-auto text-indigo-500 mb-4" />
                            <h3 className="text-xl font-semibold text-gray-900 mb-2">{item.title}</h3>
                            <p className="text-gray-500">{item.description}</p>
                        </Link>
                    </motion.div>
                ))}
            </div>
        </div>
    );
};

export default Home;